export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_PHONE = 'LOGIN_PHONE';
export const CONFIRM_PHONE = 'CONFIRM_PHONE';
export const CHANGE_PHONE = 'CHANGE_PHONE';
export const SET_BEARER_TOKEN = 'SET_BEARER_TOKEN';
export const SET_PUSH_TOKEN = 'SET_PUSH_TOKEN';
export const REGISTER_PUSH_TOKEN = 'REGISTER_PUSH_TOKEN';

export const LOAD_INITITAL_STATE = 'LOAD_INITIAL_STATE';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';

export const SET_HEADER_TITLE = 'SET_HEADER_TITLE';
export const SET_HEADER_SECTION = 'SET_HEADER_SECTION';
export const SET_HEADER_BUTTON = 'SET_HEADER_BUTTON';
export const SET_HEADER_MENU = 'SET_HEADER_MENU';

export const GET_LISTS = 'GET_LISTS';
export const GET_USER = 'GET_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';
export const UPDATE_PROFILE_VALUE = 'UPDATE_PROFILE_VALUE';
export const UPLOAD_PROFILE_VALUES = 'UPLOAD_PROFILE_VALUES';

export const NOTIFICATION_MESSAGE = 'NOTIFICATION_MESSAGE';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const SYNC_NOTIFICATIONS = 'SYNC_NOTIFICATIONS';
export const UPLOAD_NOTIFICATIONS = 'UPLOAD_NOTIFICATIONS';

export const SET_CURRENT_TRAINING_DAY = 'SET_CURRENT_TRAINING_DAY';
export const GET_TRAINING_PROGRAMS = 'GET_TRAINING_PROGRAMS';
export const SET_CURRENT_TRAINING_PROGRAM = 'SET_CURRENT_TRAINING_PROGRAM';

export const GET_NUTRITION_PROGRAM = 'GET_NUTRITION_PROGRAM';
export const UPDATE_NUTRITION_PREFERENCE = 'UPDATE_NUTRITION_PREFERENCE';
export const SYNC_NUTRITION_PREFERENCES = 'SYNC_NUTRITION_PREFERENCES';

export const GET_PHOTOS = 'GET_PHOTOS';
export const ADD_PHOTO = 'ADD_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_PHOTOS = 'DELETE_PHOTOS';
export const UPLOAD_PHOTOS = 'UPLOAD_PHOTOS';
export const UPLOAD_FILE = 'UPLOAD_FILE';

export const ADD_MEASUREMENT = 'ADD_MEASUREMENT';
export const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
export const SYNC_MEASUREMENTS = 'SYNC_MEASUREMENTS';
export const UPLOAD_MEASUREMENTS = 'UPLOAD_MEASUREMENTS';

export const ADD_TRAINING_SESSION = 'ADD_TRAINING_SESSION';
export const ADD_TRAINING_SESSION_ITEM = 'ADD_TRAINING_SESSION_ITEM';
export const GET_TRAINING_SESSIONS = 'GET_TRAINING_SESSIONS';
export const SAVE_TRAINING_SESSION = 'SAVE_TRAINING_SESSION';
export const SYNC_TRAINING_SESSIONS = 'SYNC_TRAINING_SESSIONS';

export const UPLOAD_EVERYTHING = 'UPLOAD_EVERYTHING';
export const UPLOAD_TRAINING_SESSIONS = 'UPLOAD_TRAINING_SESSIONS';

export const REQUEST_PHASE = 'request';
export const RESPONSE_PHASE = 'response';
export const FAIL_PHASE = 'fail';
export const RESET_PHASE = 'reset';

export const request = (type) => `${type}/async:${REQUEST_PHASE}`;
export const response = (type) => `${type}/async:${RESPONSE_PHASE}`;
export const fail = (type) => `${type}/async:${FAIL_PHASE}`;
export const reset = (type) => `${type}/async:${RESET_PHASE}`;
