require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
use_modular_headers!

target 'on_life' do
	config = use_native_modules! 

	use_react_native!(
		:path => config[:reactNativePath],
		# to enable hermes on iOS, change `false` to `true` and then install pods
		:hermes_enabled => false
	)

	pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
	pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
	pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true


	target 'on_lifeTests' do
		inherit! :complete
		# Pods for testing
	end

	post_install do |installer|
		react_native_post_install(installer)

		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
					config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
				end
			end
		end
	end
end
